//-----------------------------------------------------------------------
// <copyright file="Secrets.cs" company="Disney Interactive">
//     Copyright (c) 2017 Disney Interactive. All rights reserved.
// </copyright>
// <author>Adam "Bread" Slesinger</contact>
// <contact>DITPI Team</contact>
//-----------------------------------------------------------------------

using System.Reflection;

namespace Disney.ForceVision
{
	/// <summary>
	/// Used for accessing injected secrets.
	/// </summary>
	/// <remarks>
	/// This is a partial class which only contains a method to access constants that are supplied by a
	/// corresponding untracked partial class which is autogenerated at build time, or by a developer for local
	/// development. This satisfies our Security requirement of not storing secret values in source code. 
	/// </remarks>
	public partial class VaultSecrets
	{
		public static string GetSecretValue(string name)
		{
			name = name.ToUpper();
			FieldInfo info = typeof(VaultSecrets).GetField(name);
			return info == null ? string.Empty : (string)info.GetValue(null);
		}        
	}
}